version: "3"

services:
  mongo:
    image: mongo:4.1.12-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  node:
    build: .
    ports:
      - 4000:4000
